export const SET_AUTHENTICATED_USER_SUCCESS = 'SET_AUTHENTICATED_USER_SUCESS';
export const SET_AUTHENTICATED_USER_START = 'SET_AUTHENTICATED_USER_START';
export const AUTHENTICATED_USER_LOGOUT = 'AUTHENTICATED_USER_LOGOUT';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_SCREAMS_START = 'FETCH_SCREAMS_START';
export const FETCH_SCREAMS_SUCCESS = 'FETCH_SCREAMS_SUCCESS';
export const FETCH_SCREAMS_FAIL = 'FETCH_SCREAMS_FAIL';

export const LIKE_SCREAM = 'LIKE_SCREAM';
export const UNLIKE_SCREAM = 'UNLIKE_SCREAM';
export const DELETE_SCREAM = 'DELETE_SCREAM';
export const SET_NEW_SCREAM_START = 'SET_NEW_SCREAM_START';
export const SET_NEW_SCREAM_SUCESS = 'SET_NEW_SCREAM_SUCESS';
export const SET_NEW_SCREAM_FAIL = 'SET_NEW_SCREAM_FAIL';
export const FETCH_SCREAM_DETAIL_START = 'FETCH_SCREAM_DETAIL_START';
export const FETCH_SCREAM_DETAIL_SUCCESS = 'FETCH_SCREAM_DETAIL_SUCCESS';
export const FETCH_SCREAM_DETAIL_FAIL = 'FETCH_SCREAM_DETAIL_FAIL';
