export const SET_AUTHENTICATED_USER_SUCCESS = 'SET_AUTHENTICATED_USER_SUCESS';
export const SET_AUTHENTICATED_USER_START = 'SET_AUTHENTICATED_USER_START';
export const AUTHENTICATED_USER_LOGOUT = 'AUTHENTICATED_USER_LOGOUT';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
